dist: bionic
language: minimal

services:
  - docker

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

script:
  - DOCKER_BUILDKIT=1 docker build --build-arg BRANCH_NAME='$TRAVIS_BRANCH' --build-arg COMMIT_SHA=$TRAVIS_COMMIT
      -t registry.heroku.com/unofficial-vocadb-ntf-reader/web .

deploy:
  provider: script
  script:
    docker push registry.heroku.com/unofficial-vocadb-ntf-reader/web
    heroku container:release web --app unofficial-vocadb-ntf-reader
  on:
    branch: master
