name: Backend Build

on:
  push:
    paths:
      - backend/**
      - .github/workflows/backend_*

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo build --release --all-features
#      - run: cargo clippy --all-targets --all-features

      - uses: redhat-actions/podman-login@v1
        if: github.ref_name == 'master'
        with:
          registry: ghcr.io/${{ github.actor }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: podman build --file Dockerfile --tag ghcr.io/${{ github.repository }}:${{ github.sha }} .
        if: github.ref_name == 'master'
      - run: podman push ghcr.io/${{ github.repository }}:${{ github.sha }}
        if: github.ref_name == 'master'
