name: Backend Build

on:
  push:
    paths:
      - backend/**
      - .github/workflows/backend_*

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo build --release --all-features
      - run: cargo clippy --all-targets --all-features
