name: Backend Deploy

on:
  workflow_run:
    workflows:
      - Backend Build
    branches:
      - master
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Deploy
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io/${{ github.actor }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: podman build ghcr.io/${{ github.repository }} -t ${{ github.sha }}
      - run: podman push ghcr.io/${{ github.repository }}:${{ github.sha }}
