name: Backend Build

on:
  push:
    paths:
      - backend/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo build --release --all-features
        working-directory: backend
